/* eslint-disable  func-names */
/* eslint-disable max-len */
/* eslint quote-props: ['error', 'consistent']*/
// https://www.pro-football-reference.com/teams/nwe/2017_roster.htm
// https://d395i9ljze9h3x.cloudfront.net/req/20171109/images/headshots/AlleDw00.jpg

module.exports = {
    'RECIPE_EN_GB': {
        '32': 'That is Devon McCourty GB number',
        'thirty two': 'That is Devon McCourty GB text',
        'snow golem': 'A snow golem can be created by placing a pumpkin on top of  two snow blocks on the ground.',
        'pillar quartz block': 'A pillar of quartz can be obtained by placing a block of quartz on top of a block of quartz in mine craft.',
        'firework rocket': 'A firework rocket can be crafted by placing a firework star in the left middle square, a piece of paper in the center square, and gunpowder in the right middle square in a crafting table. Similar to a firework star, a firework rocket can have more gunpowder added in the bottom row to increase the duration of a rocket.',
        'rabbit stew': 'Rabbit stew can be crafted by placing cooked rabbit in the top middle square, a carrot in the middle left square, a baked potato in the center square, any type of mushroom in the middle right square, and a bowl in the bottom middle square.',
        'cauldron': 'A cauldron can be created by placing iron ingots in all squares but the top middle and very center squares in a crafting table.',
        'stone shovel': 'GB All types of shovels can be crafted by placing the desired material in the top middle square, and then sticks in the two squares directly beneath that in a crafting table.',
        'black stained glass pane': 'Any type of stained glass pane can be crafted by placing the same color stained glass, horizontally, in the bottom two rows.',
    },
    'RECIPE_EN_US': {
        '83':   'Allen Dwayne TE 6-3 265 27 6 00 Clemson',
        '6':    'Allen Ryan P 6-2 220 27 5 01 Louisiana Tech',
        '80':   'Amendola Danny WR 5-11 190 32 9 00 Texas Tech',
        '60':   'Andrews David C 6-3 295 25 3 00 Georgia',
        '29':   'Bademosi Johnson CB 6-0 206 27 6 00 Stanford',
        '38':   'Bolden Brandon RB 5-11 220 27 6 00 Mississippi',
        '12':   'Brady Tom QB 6-4 225 40 18 00 Michigan',
        '97':   'Branch Alan DL 6-6 350 33 11 99 Michigan',
        '85':   'Britt Kenny WR 6-3 223 29 9 00 Rutgers',
        '90':   'Brown Malcom DL 6-2 320 23 3 01 Texas',
        '34':   'Burkhead Rex RB 5-10 210 27 5 00 Nebraska',
        '70':   'Butler Adam DL 6-4 300 23 R https://static.nfl.com/static/content/public/static/img/fantasy/transparent/200x200/BUT106408.png Vanderbilt',
        '21':   'Butler Malcolm CB 5-11 190 27 4 01 West Alabama',
        '49':   'Cardona Joe LS 6-3 245 25 3 00 Navy',
        '23':   'Chung Patrick S 5-11 215 30 9 99 Oregon',
        '14':   'Cooks Brandin WR 5-10 189 24 4 00 Oregon State',
        '74':   'Croston Cole OL 6-5 315 24 R https://static.nfl.com/static/content/public/static/img/fantasy/transparent/200x200/CRO522680.png Iowa',
        '46':   'Develin James FB 6-3 255 29 5 00 Brown',
        '13':   'Dorsett Phillip WR 5-10 185 25 3 00 Miami (Fla.)',
        '71':   'Fleming Cameron OL 6-6 320 25 4 00 Stanford',
        '59':   'Flowers Marquis LB 6-3 250 25 4 00 Arizona',
        '98':   'Flowers Trey DL 6-2 265 24 3 00 Arkansas',
        '35':   'Gillislee Mike RB 5-11 219 27 5 00 Florida',
        '24':   'Gilmore Stephon CB 6-1 190 27 6 00 South Carolina',
        '3':    'Gostkowski Stephen K 6-1 215 33 12 20 Memphis',
        '50':   'Grigsby Nicholas LB 6-2 230 25 2 01 Pittsburgh',
        '96':   'Grissom Geneo DL 6-4 265 25 3 00 Oklahoma',
        '87':   'Gronkowski Rob TE 6-6 265 28 8 00 Arizona',
        '93':   'Guy Lawrence DL 6-4 305 27 7 00 Arizona State',
        '30':   'Harmon Duron DB 6-1 205 26 5 00 Rutgers',
        '45':   'Harris David LB 6-2 250 33 11 99 Michigan',
        '92':   'Harrison James LB 6-0 242 39 15 23 Kent State',
        '15':   'Hogan Chris WR 6-1 210 29 5 00 Monmouth (N.J.)',
        '47':   'Hollister Jacob TE 6-4 239 24 R https://static.nfl.com/static/content/public/static/img/fantasy/transparent/200x200/HOL292467.png Wyoming',
        '2':    'Hoyer Brian QB 6-2 215 32 9 00 Michigan State',
        '94':   'JeanFrancois Ricky DL 6-3 313 31 9 99 LSU',
        '31':   'Jones Jonathan DB 5-10 190 24 2 03 Auburn',
        '75':   'Karras Ted G 6-4 305 24 2 00 Illinois',
        '36':   'King Brandon DB 6-2 220 24 3 02 Auburn',
        '55':   'Lee Eric DL 6-3 260 23 1 00 South Florida',
        '33':   'Lewis Dion RB 5-8 195 27 6 00 Pittsburgh',
        '69':   'Mason Shaq OL 6-1 310 24 3 01 Georgia Tech',
        '32':   'McCourty Devin DB 5-10 195 30 8 99 Rutgers',
        '37':   'Richards Jordan DB 5-11 210 24 3 00 Stanford',
        '52':   'Roberts Elandon LB 6-0 235 23 2 00 Houston',
        '25':   'Rowe Eric DB 6-1 205 25 3 00 Utah',
        '18':   'Slater Matthew WR 6-0 205 32 10 00 UCLA',
        '77':   'Solder Nate OT 6-8 325 29 7 00 Colorado',
        '62':   'Thuney Joe G 6-5 305 25 2 00 North Carolina State',
        '53':   'VanNoy Kyle LB 6-3 243 26 4 https://static.nfl.com/static/content/public/static/img/fantasy/transparent/200x200/VAN656604.png Brigham Young',
        '68':   'Waddle LaAdrian OL 6-6 315 26 5 01 Texas Tech',
        '28':   'White James RB 5-10 205 25 4 02 Wisconsin',
        '91':   'Wise Deatrich DL 6-5 271 23 R 00 Arkansas',

    },
    'RECIPE_DE_DE': {
        'schneegolem': 'Ein Schneegolem kann erschaffen werden, indem ein Kürbis auf zwei auf dem Boden stehende Schneeblöcke gesetzt wird.',
        'quarzsäule': 'Eine Quarzsäule erhält man, indem in Minecraft ein Quarzblock auf einem Quarzblock platziert wird.',
        'feuerwerksrakete': 'Eine Feuerwerksrakete kann gecraftet werden, indem ein Feuerwerksstern in das linke mittlere Feld, ein Blatt Papier in das mittlere Feld und Schwarzpulver in das rechte mittlere Feld der Werkbank gelegt wird. Ähnlich wie bei einem Feuerwerksstern kann einer Feuerwerksrakete in der unteren Reihe zusätzliches Schwarzpulver hinzugefügt werden, um die Dauer der Rakete zu verlängern.',
        'kaninchenragout': 'Kaninchenragout kann gecraftet werden, indem ein Gekochtes Kaninchen in das obere mittlere Feld, eine Karotte in das linke mittlere Feld, eine Ofenkartoffel in das Feld ganz in der Mitte, eine beliebige Pilzart in das rechte mittlere Feld und eine Schüssel in des untere mittlere Feld platziert wird.',
        'kessel': 'Ein Kessel kann hergestellt werden, indem Eisenbarren in alle Felder der Werkbank mit Ausnahme des oberen mittleren Feldes und des Feldes ganz in der Mitte gelegt werden.',
        'steinschaufel': 'Jede Art von Schaufel lässt sich craften, indem auf der Werkbank das gewünschte Material in das obere mittlere Feld gelegt wird und dann Stöcke in die beiden direkt darunter befindlichen Felder platziert werden.',
        'schwarz gefärbte glasscheibe': 'Alle verschiedenen gefärbten Glasscheiben lassen sich craften, indem Glas gleicher Farbe in den unteren beiden Reihen horizontal platziert wird.',
    },
};
